theme: minima
title: qhÂ·china lab
description: Quantitative Humanities Lab for Chinese Studies
baseurl: ""
url: "https://www.qhchina.org"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

# SASS settings
sass:
  sass_dir: _sass
  style: compressed

# Navigation
header_pages:
  - about/index.md
  - projects/index.md
  - resources/index.md
  - pkg_docs/index.md

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# GitHub metadata
github_username: mcjkurz
repository: mcjkurz/qhchina

# Custom variables
show_downloads: true
logo: assets/img/logo.png

# Google Analytics (replace with your ID if needed)
# google_analytics: UA-XXXXXXXXX-X

# Visitor counter
goatcounter_code: qhchina # This will create the URL qhchina.goatcounter.com

# Social media links
# github_username: mcjkurz
# repository: mcjkurz/qhchina

# GitHub Pages compatibility
github: [metadata]